import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useUUID } from "@/utils/useUUID";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const id = useUUID();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="TestPage__Container">
       {/* // id as key is still valid */}
        <p key={id}>{id}</p> 
      </div>
    </>
  );
}
